### ISSUE TITLE
建议使用大盔甲架...

### ISSUE THREAD

**Issue by Score2** [Arasple/TrHologram#1]
建议使用大盔甲架。在使用ViaVersion时，有些客户端版本中，原本的小型盔甲架会被强制转换为大盔甲架，从而全息字会被抬高一点，影响体验。

**Comment by Arasple** [comment]
Hd也没用大盔甲架... 它有这种情况吗

**Comment by Score2** [comment]
> Hd也没用大盔甲架... 它有这种情况吗

是的，以往我使用HD，在ViaVersion跨版本的作用下，有些版本进入服务器会被强制转换为大盔甲架，直到我后来修改了HD显示的盔甲架为大盔甲架后，问题才得到解决

**Comment by Arasple** [comment]
```YAML
# Options
OPTIONS:
  # Should use small holograms (Do not recommend disable)
  ARMORSTAND-SMALL: true
```
